// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "登录用户",
                "parameters": [
                    {
                        "description": "请求body参数",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "刷新Jwt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token令牌",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/result.Result"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "description": "请求body参数",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterResponse"
                        }
                    }
                }
            }
        },
        "/api/user/info": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token令牌",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.InfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/result.Result"
                        }
                    }
                }
            }
        },
        "/api/user/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "每页页数(数量)",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "当前页数",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/result.Result"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/user.User"
                }
            }
        },
        "auth.RefreshResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "age",
                "email",
                "password",
                "uname"
            ],
            "properties": {
                "age": {
                    "description": "用户年龄",
                    "type": "integer",
                    "maximum": 200,
                    "minimum": 0
                },
                "email": {
                    "description": "用户邮箱",
                    "type": "string"
                },
                "password": {
                    "description": "用户密码",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                },
                "uname": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 2
                }
            }
        },
        "auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/user.User"
                }
            }
        },
        "code.ECode": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                100,
                101,
                102,
                103,
                104,
                105,
                106,
                107
            ],
            "x-enum-comments": {
                "ECode_AuthExpire": "授权过期",
                "ECode_AuthInvalid": "授权无效",
                "ECode_AuthNotLogin": "未授权登录",
                "ECode_AuthUserError": "用户或密码错误",
                "ECode_EmailExist": "邮箱已存在",
                "ECode_EmailNotExist": "邮箱不存在",
                "ECode_Param": "参数错误",
                "ECode_Service": "服务错误",
                "ECode_Success": "成功",
                "ECode_Unknown": "未知错误",
                "ECode_UserExist": "用户已存在",
                "ECode_UserNotExist": "用户不存在"
            },
            "x-enum-varnames": [
                "ECode_Success",
                "ECode_Unknown",
                "ECode_Service",
                "ECode_Param",
                "ECode_AuthNotLogin",
                "ECode_AuthExpire",
                "ECode_AuthInvalid",
                "ECode_AuthUserError",
                "ECode_UserExist",
                "ECode_UserNotExist",
                "ECode_EmailExist",
                "ECode_EmailNotExist"
            ]
        },
        "result.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/code.ECode"
                        }
                    ]
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "响应信息",
                    "type": "string"
                }
            }
        },
        "user.InfoResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/user.User"
                }
            }
        },
        "user.ListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.User"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "email": {
                    "description": "用户邮箱",
                    "type": "string"
                },
                "uid": {
                    "description": "用户ID",
                    "type": "integer"
                },
                "uname": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API接口",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
